// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXZ13euHjeOErqeRy1-CwwWCZhxHnEO6o',
    appId: '1:95924328756:web:559f28fb6ad0f19cb9ed61',
    messagingSenderId: '95924328756',
    projectId: 'final-project-section-2',
    authDomain: 'final-project-section-2.firebaseapp.com',
    storageBucket: 'final-project-section-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc1mKeuapAR3tvzNOZntFj9LYKVZC8R5g',
    appId: '1:95924328756:android:683f15f3008a01b8b9ed61',
    messagingSenderId: '95924328756',
    projectId: 'final-project-section-2',
    storageBucket: 'final-project-section-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuB94__yIGxh-T7EB0HxCD3E0Hhlw7ujY',
    appId: '1:95924328756:ios:12908f875f795742b9ed61',
    messagingSenderId: '95924328756',
    projectId: 'final-project-section-2',
    storageBucket: 'final-project-section-2.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceMiniShoppingCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuB94__yIGxh-T7EB0HxCD3E0Hhlw7ujY',
    appId: '1:95924328756:ios:12908f875f795742b9ed61',
    messagingSenderId: '95924328756',
    projectId: 'final-project-section-2',
    storageBucket: 'final-project-section-2.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceMiniShoppingCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXZ13euHjeOErqeRy1-CwwWCZhxHnEO6o',
    appId: '1:95924328756:web:03d821afae507c61b9ed61',
    messagingSenderId: '95924328756',
    projectId: 'final-project-section-2',
    authDomain: 'final-project-section-2.firebaseapp.com',
    storageBucket: 'final-project-section-2.firebasestorage.app',
  );
}
